---
- name: Bounce Nodes
  serial: 1
  hosts: all
  gather_facts: false
  tasks:
    - name: Drain node
      local_action:
        module: command
        _raw_params: "kubectl drain --delete-local-data --ignore-daemonsets {{inventory_hostname}}"
      ignore_errors: True
    - name: Reboot
      reboot:
      become: yes
    - name: Uncordon node
      local_action:
        module: command
        _raw_params: "kubectl uncordon {{inventory_hostname}}"
